image:
  - Visual Studio 2019
clone_folder: c:\projects\source

environment:
    PYTHON: "C:\\Python39-x64\\python.exe"

build_script:
- cmd: >-
    mkdir build

    cd build

    set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\Python\Python39\Scripts

    "%PYTHON%" -m pip install --user conan

    cmake c:\projects\source -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE:STRING=Debug

    cmake --build . --config "Debug"

test_script:
- cmd: ctest -C Debug

