REM SET BUILD_DIR=".msvc_ide"
SET BUILD_DIR="./build"

SET BOOST_VER=1.67.0
SET CMAKE_VER=3.11.3

SET USER_LIBS=%USERPROFILE%\libraries

SET BOOST_LIBRARYDIR=%USER_LIBS%\Boost\%BOOST_VER%\lib\msvc-14.1\x64
SET BOOST_INCLUDEDIR=%USER_LIBS%\Boost\%BOOST_VER%\include

echo %BOOST_LIBRARYDIR%

mkdir %BUILD_DIR%
pushd %BUILD_DIR%

REM %USER_LIBS%\CMake\%CMAKE_VER%\bin\cmake -G "Visual Studio 14 2015 Win64" ..
%USER_LIBS%\CMake\%CMAKE_VER%\bin\cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -T host=x64 ..

popd
