## Boost

if (MSVC)
	set (DEFAULT_BOOST_VERSION 1.55.0)

	if (NOT DEFINED BOOST_VERSION)
		set (BOOST_VERSION ${DEFAULT_BOOST_VERSION})
	endif()

	set (BOOST_DIR ${MR_ROOT}/Boost/${BOOST_VERSION})
	set (BOOST_INCLUDE ${BOOST_DIR}/include)
	set (BOOST_LIB ${BOOST_DIR}/lib/${QR_COMPILER}/${QR_PLATFORM})

endif ()

if (CMAKE_COMPILER_IS_GNUCXX)
	set (DEFAULT_BOOST_VERSION 1.53.0)

	set (BOOST_DIR ${DEVPKGS_PATH})
	set (BOOST_INCLUDE ${DEVPKGS_PATH}/include)
	set (BOOST_LIB ${DEVPKGS_PATH}/lib)

	set (lib_boost_atomic				boost_atomic)
	set (lib_boost_chrono				boost_chrono)
	set (lib_boost_context				boost_context)
	set (lib_boost_date_time			boost_date_time)
	set (lib_boost_exception			boost_exception)
	set (lib_boost_filesystem			boost_filesystem)
	set (lib_boost_graph				boost_graph)
	set (lib_boost_iostreams			boost_iostreams)
	set (lib_boost_locale				boost_locale)
	set (lib_boost_math_c99				boost_math_c99)
	set (lib_boost_math_c99f			boost_math_c99f)
	set (lib_boost_math_c99l			boost_math_c99l)
	set (lib_boost_math_tr1				boost_math_tr1)
	set (lib_boost_math_tr1f			boost_math_tr1f)
	set (lib_boost_math_tr1l			boost_math_tr1l)
	set (lib_boost_prg_exec_monitor		boost_prg_exec_monitor)
	set (lib_boost_program_options		boost_program_options)
	set (lib_boost_python3				boost_python3)
	set (lib_boost_python				boost_python)
	set (lib_boost_random				boost_random)
	set (lib_boost_regex				boost_regex)
	set (lib_boost_serialization		boost_serialization)
	set (lib_boost_signals				boost_signals)
	set (lib_boost_system				boost_system)
	set (lib_boost_test_exec_monitor	boost_test_exec_monitor)
	set (lib_boost_thread				boost_thread)
	set (lib_boost_timer				boost_timer)
	set (lib_boost_unit_test_framework	boost_unit_test_framework)
	set (lib_boost_wave					boost_wave)
	set (lib_boost_wserialization		boost_wserialization)
endif()

include_directories (${BOOST_INCLUDE})
link_directories (${BOOST_LIB})
